wget https://raw.githubusercontent.com/googlefonts/noto-emoji/main/svg/emoji_u1f45f.svg
wget https://raw.githubusercontent.com/googlefonts/noto-emoji/main/svg/emoji_u1f97f.svg
wget https://raw.githubusercontent.com/googlefonts/noto-emoji/main/svg/emoji_u1f460.svg
wget https://raw.githubusercontent.com/googlefonts/noto-emoji/main/svg/emoji_u1f45e.svg
wget https://raw.githubusercontent.com/googlefonts/noto-emoji/main/svg/emoji_u1f97e.svg
wget https://raw.githubusercontent.com/googlefonts/noto-emoji/main/svg/emoji_u1f462.svg
wget https://raw.githubusercontent.com/googlefonts/noto-emoji/main/svg/emoji_u1f461.svg
wget https://raw.githubusercontent.com/googlefonts/noto-emoji/main/svg/emoji_u1fa70.svg
wget https://raw.githubusercontent.com/googlefonts/noto-emoji/main/svg/emoji_u26f8.svg
wget https://raw.githubusercontent.com/googlefonts/noto-emoji/main/svg/emoji_u1f6fc.svg
wget https://raw.githubusercontent.com/googlefonts/noto-emoji/main/svg/emoji_u1fa74.svg
wget https://raw.githubusercontent.com/googlefonts/noto-emoji/main/svg/emoji_u1f3bf.svg
